"""Boilerplate detection and removal for Nepali/English web content.

Centralizes boilerplate logic previously scattered across enrichment.py and
control.py.  Provides:

- Per-document cleaning (nav, footer, sidebar removal)
- Cross-document domain profile learning
- Devanagari-aware line classification
"""

from __future__ import annotations

import re
import logging
from collections import Counter
from typing import Dict, List, Optional, Set

from .normalize import devanagari_ratio

logger = logging.getLogger("nepali_corpus.boilerplate")

# ── Known boilerplate keywords (Nepali + English) ──────────────────────

NAV_KEYWORDS_EN = {
    "check mail", "english", "nepali", "toggle navigation", "home",
    "about us", "skip to content", "search for:",
    "facebook", "twitter", "instagram", "linkedin", "youtube", "tiktok",
    "viber", "whatsapp", "telegram", "mail", "x", "rss", "feed",
    "profiles", "notices", "careers", "advertise", "contact", "login",
    "register", "search", "menu", "close", "faq", "language", "ne", "en",
    "sign in", "join", "welcome", "forgot password", "get help",
    "download now", "view all", "read more", "search archives",
    "location", "address", "phone", "email",
}

NAV_KEYWORDS_NE = {
    "राजनीति", "खेलकुद", "समाचार", "विचार", "अन्तर्वार्ता", "अन्तरवार्ता", "मनोरञ्जन",
    "स्वास्थ्य", "समाज", "भिडियो", "ताजा अपडेट", "अर्थ", "प्रवास",
    "मुख्य समाचार", "शिक्षा", "विश्व", "पर्यटन", "राशिफल", "जीवनशैली",
    "विविध", "फोटो फिचर", "सूचना प्रविधि", "अर्थ र विकास", "पालिका खबर",
    "अन्तर्राष्ट्रिय", "सम्पर्क", "हाम्रो बारेमा", "हाम्रो टिम",
    "विज्ञापन", "देश", "प्रदेश", "फोटो", "गृहपृष्ठ", "ताजा", "सबै",
    "सम्पर्क नं", "फोन नं", "इमेल", "ठेगाना", "वेबसाइट",
    "नयाँ", "मुख्य", "पृष्ठ", "गृह", "कला", "साहित्य", "रोचक खबर",
    "प्रदेश खबर", "धर्म / राशिफल", "धर्म/राशिफल", "अर्थ–व्यवसाय",
    "कर्णाली", "गण्डकी", "लुम्बिनी", "बागमती", "मधेश", "कोशी", "सुदूरपश्चिम",
}

# Merge into a single set for quick lookup
TOP_MENU_KEYWORDS = NAV_KEYWORDS_EN | NAV_KEYWORDS_NE

# Short nav words (for lines with ≤3 words)
SHORT_NAV_WORDS = {
    "search", "menu", "close", "login", "register", "contact", "faq",
    "language", "ne", "en", "नयाँ", "ताजा", "सबै", "गृहपृष्ठ", "मुख्य",
    "समाचार", "पृष्ठ", "गृह", "sign in", "join", "welcome",
    "forgot password", "get help", "about us",
}

# Fixed bad-pattern strings to strip from final text
BAD_PATTERNS = [
    "Language : नेपाली ENGLISH", "Language : English नेपाली",
    "Skip to content", "Toggle navigation", "Search for:",
    "Print PDF", "Share this:", "Sign in / Join",
    "Log into your account", "Recover your password",
    "Forgot your password? Get help", "Welcome! Log into your account",
    "A password will be e-mailed to you.", "Nepali news popular site",
    "Download Now", "Read More", "View PDF", "Supporting Documents",
    "Share On", "Ward Contact Number", "कर्मचारीहरुको विवरण",
    "यो पेज सेयर गर्नुहोस्", "थप जानकारीको लागि",
    "अगाडी जानुहोस्", "पछाडी जानुहोस्", "महत्वपूर्ण लिङ्कहरू",
    "Copyright © 2026 All Rights Reserved",
    "यो सामग्री पढेर तपाइँलाई कस्तो लाग्यो ?",
    "प्रतिक्रिया दिनुहोस्", "माया लाग्यो", "ताजुब लाग्यो",
    "दुःख लाग्यो", "ठीकै लाग्यो", "पारो तातो", "हाँसो लाग्यो",
    "मन पर्‍यो", "सम्बन्धित सामग्रीहरू",
    "Comments", "Shares", "News Summary", "shares",
    "Generated by OK AI. Editorially reviewed.",
    "News Views:", "Share:",
    "Copyright © 2026 All Rights Reserved. | www.sansarnews.com | Maintained by self",
    "ट्रेन्डिङ", "News Tags:", "Tag:",
    "धेरै कमेन्ट गरिएका", "Twitter Feed", "Twitter", "Advertisment",
    "tweet", "Online Khabar", "0",
    "अर्थ–व्यवसाय", "प्रवास", "ब्लग", "अन्तरवार्ता", "प्रदेश खबर",
    "धर्म", "राशिफल", "अन्तर्राष्ट्रिय समाचार", "स्वास्थ्य", "साहित्य",
    "खेलकुद", "कला", "रोचक खबर",
    "Your browser does not support the audio element.", "Listen News",
    "होम", "समाचार", "अन्तर्राष्ट्रिय", "आर्थिक", "ट्राभल", "विचार", "स्वास्थ्य",
    "मनोरञ्जन", "सूचना-प्रविधि", "राजनीति", "सुरक्षा", "खेलकुद", "अन्य",
    "जीवनशैली", "स्टोरी", "प्रवास", "धर्म /", "संस्कृति", "इमिग्रेसन",
    "रोजगार", "पत्रपत्रिका", "विचित्र संसार", "सम-सामयिक", "समाज",
    "साहित्य", "स्थानीय", "युटिलिटीज्", "मिति परिवर्तन", "प्रीति टु युनिकोड",
    "युनिकोड टु प्रीति", "रोमन टु युनिकोड", "विदेशी मुद्रा", "सुन/चाँदी",
    "वायु गुणस्तर सूचकांक", "तरकारी", "भिडियो", "पोडकास्ट", "लगइन",
    "ताजा र विश्वसनीय समाचार, विचार, अन्तवार्ता, विश्लेषण लगायत दैनिक आवश्यक जानकारीका लागि खबरहब डटकम हेर्नुहोस।",
    "©2 26 Khabarhub सर्वाधिकार सुरक्षित पेभलियन मिडिया प्रा.लि",
    "| Site By :",
]

# Navigation items seen in training data
NAV_KEYWORDS_NE.update({
    "ब्लग", "साहित्य", "स्वास्थ्य", "खेलकुद", "प्रवास", "धर्म / राशिफल",
    "प्रदेश खबर", "अर्थ–व्यवसाय", "अन्तर्राष्ट्रिय समाचार", "कला",
    "अन्तरवार्ता", "रोचक खबर", "Sansar News", "ट्रेन्डिङ",
    "धर्म", "राशिफल", "होम", "समाचार", "अन्तर्राष्ट्रिय", "आर्थिक",
    "ट्राभल", "विचार", "मनोरञ्जन", "सूचना-प्रविधि", "राजनीति",
    "सुरक्षा", "अन्य", "जीवनशैली", "स्टोरी", "संस्कृति", "इमिग्रेसन",
    "रोजगार", "पत्रपत्रिका", "विचित्र संसार", "सम-सामयिक", "समाज",
    "स्थानीय", "युटिलिटीज्", "मिति परिवर्तन", "प्रीति टु युनिकोड",
    "युनिकोड टु प्रीति", "रोमन टु युनिकोड", "विदेशी मुद्रा", "सुन/चाँदी",
    "वायु गुणस्तर सूचकांक", "तरकारी", "भिडियो", "पोडकास्ट", "लगइन",
})

# File extension patterns
_FILE_EXTS = {".pdf", ".docx", ".doc", ".xlsx", ".xls", ".png", ".jpg", ".jpeg"}

# Junk keywords for cross-document filtering
JUNK_KEYWORDS = {
    "facebook", "twitter", "instagram", "linkedin", "youtube", "tiktok",
    "viber", "whatsapp", "telegram", "mail", "x", "rss", "feed",
    "profiles", "notices", "careers", "advertise", "contact", "login",
    "register", "search", "menu", "close",
}

# ── Regexes ─────────────────────────────────────────────────────────────

_DATE_RE = re.compile(r"^\d{4}[-/]\d{2}[-/]\d{2}$")
_RELATIVE_TIME_RE = re.compile(r"^\d+\s+(महिना|दिन|अगाडी|month|day|year|ago)", re.IGNORECASE)
_PHONE_RE = re.compile(r"(\+?977[- ]?)?\d{2}[- ]?\d{7}|\d{1,2}-\d{6,7}")
_SEPARATOR_RE = re.compile(r"^[ \-._=#*|·•]+$")
_CONTACT_LABELS = {
    "email:", "phone:", "fax:", "address:", "website:",
    "इमेल:", "फोन:", "ठेगाना:", "फ्याक्स:",
}


# ── Per-document cleaning ───────────────────────────────────────────────

def clean_extracted_text(text: str) -> str:
    """Remove boilerplate from a single extracted document.

    This replaces the inline post-processing previously in enrichment.py.
    """
    if not text:
        return ""

    lines = [ln.strip() for ln in text.split("\n")]
    lines = [ln for ln in lines if ln]

    # 1. Strip leading navigation/header lines
    lines = _strip_leading_nav(lines)

    # 2. Filter technical junk lines
    lines = _filter_junk_lines(lines)

    # 3. Intra-document dedup (short duplicate lines)
    lines = _dedup_lines(lines)

    # 4. Strip known bad patterns
    result = "\n".join(lines).strip()
    result = _strip_bad_patterns(result)
    result = re.sub(r" +", " ", result)

    return result.strip()


def _strip_leading_nav(lines: List[str]) -> List[str]:
    """Remove navigation/header lines from the start of the document.

    Only strips lines that match known navigation keywords or patterns.
    Does NOT strip arbitrary English text — that would remove article content.
    """
    while lines:
        ln = lines[0]
        ln_lower = ln.lower().strip()
        ln_clean = ln_lower.replace(" ", "")

        is_boilerplate = False

        # Known keywords (exact or prefix match)
        for p in TOP_MENU_KEYWORDS:
            if ln_lower == p or ln_clean == p or (ln_lower.startswith(p) and len(ln_lower) < len(p) + 5):
                is_boilerplate = True
                break

        # Short nav word lines (≤3 words, all are nav words)
        if not is_boilerplate and len(ln.split()) <= 3:
            words = [w.strip(" |·•-").lower() for w in ln.split()]
            if words and all(w in SHORT_NAV_WORDS or w in TOP_MENU_KEYWORDS for w in words):
                is_boilerplate = True

        # Very short English-only lines (≤2 words) that are likely site chrome
        if not is_boilerplate and devanagari_ratio(ln) < 0.05 and len(ln.split()) <= 2:
            word = ln_lower.strip()
            if word in TOP_MENU_KEYWORDS or word in SHORT_NAV_WORDS:
                is_boilerplate = True

        if is_boilerplate:
            lines.pop(0)
        else:
            break

    return lines


def _filter_junk_lines(lines: List[str]) -> List[str]:
    """Remove lines that are dates, phone numbers, file names, etc."""
    clean = []
    for ln in lines:
        s = ln.strip()
        if not s:
            continue

        # File names
        if any(s.lower().endswith(ext) for ext in _FILE_EXTS):
            continue

        # Bare dates
        if _DATE_RE.match(s):
            continue

        # Relative time stamps
        if _RELATIVE_TIME_RE.search(s.lower()):
            continue

        # Phone numbers
        if _PHONE_RE.search(s):
            continue

        # Separator lines
        if _SEPARATOR_RE.match(s):
            continue

        # Contact labels
        if any(s.lower().startswith(label) for label in _CONTACT_LABELS) and len(s.split()) < 5:
            continue

        clean.append(ln)

    return clean


def _dedup_lines(lines: List[str]) -> List[str]:
    """Remove duplicate short lines within one document."""
    seen: Set[str] = set()
    result = []
    for ln in lines:
        key = ln.lower().strip()
        if key in seen and (len(key) < 200 or key.count(" ") < 10):
            continue
        result.append(ln)
        seen.add(key)
    return result


def _strip_bad_patterns(text: str) -> str:
    """Strip known fixed boilerplate strings."""
    for p in BAD_PATTERNS:
        if text.startswith(p):
            text = text[len(p):].strip()
        text = text.replace(p, " ")
    return text


# ── Cross-document boilerplate detection ────────────────────────────────

class BoilerplateDetector:
    """Learns per-domain boilerplate profiles from batches of documents.

    Tracks line frequency across documents from the same source/domain.
    Lines that appear in a high % of documents from a source are flagged
    as site-wide boilerplate (headers, footers, sidebars).
    """

    def __init__(self) -> None:
        self._domain_line_counts: Dict[str, Counter] = {}
        self._domain_doc_counts: Dict[str, int] = {}
        self._domain_profiles: Dict[str, Set[str]] = {}

    def update_profile(self, texts: List[str], domain: str) -> None:
        """Feed a batch of texts from the same domain to learn its profile."""
        if domain not in self._domain_line_counts:
            self._domain_line_counts[domain] = Counter()
            self._domain_doc_counts[domain] = 0

        for text in texts:
            if not text:
                continue
            self._domain_doc_counts[domain] += 1
            unique_lines = set(l.strip() for l in text.split("\n") if l.strip())
            for line in unique_lines:
                self._domain_line_counts[domain][line] += 1

        self._rebuild_profile(domain)

    def _rebuild_profile(self, domain: str) -> None:
        """Recompute the boilerplate set for a domain."""
        doc_count = self._domain_doc_counts.get(domain, 0)
        if doc_count < 3:
            return  # Not enough docs to establish a profile

        counts = self._domain_line_counts[domain]
        boilerplate: Set[str] = set()

        # Threshold: 80% for general lines, 90% for Nepali content-like lines
        threshold_general = max(3, int(doc_count * 0.8))
        threshold_content = max(3, int(doc_count * 0.9))

        for line, count in counts.items():
            ratio = devanagari_ratio(line)
            is_content_like = ratio > 0.6 and len(line) > 40

            if is_content_like:
                if count >= threshold_content:
                    boilerplate.add(line)
            else:
                if count >= threshold_general:
                    boilerplate.add(line)

            # Always add known junk keyword lines
            if line.lower().strip() in JUNK_KEYWORDS:
                boilerplate.add(line)

        self._domain_profiles[domain] = boilerplate

    def clean_document(self, text: str, domain: str) -> str:
        """Remove domain-specific boilerplate from a document."""
        profile = self._domain_profiles.get(domain, set())
        if not profile:
            return text

        lines = text.split("\n")
        cleaned = []
        for line in lines:
            s = line.strip()
            if not s:
                continue

            if s in profile:
                continue

            # Multi-keyword junk lines
            words = [w.strip(",|·•-") for w in s.lower().split()]
            if all(w in JUNK_KEYWORDS for w in words) and len(words) <= 5:
                continue

            # Common signatures
            s_low = s.lower()
            if "@" in s and "." in s:
                continue
            if "©" in s or "all rights reserved" in s_low:
                continue
            if "designed" in s_low and "developed" in s_low:
                continue

            cleaned.append(s)

        return "\n".join(cleaned).strip()

    def clean_batch(
        self,
        texts_with_domains: List[tuple],
        min_text_len: int = 200,
        min_devanagari: float = 0.4,
    ) -> List[Optional[str]]:
        """Clean a batch of (text, domain) pairs.

        Also updates profiles from the batch.  Returns list of cleaned
        texts (or None if the text doesn't pass quality filters).
        """
        # Group by domain
        domain_texts: Dict[str, List[str]] = {}
        for text, domain in texts_with_domains:
            domain_texts.setdefault(domain, []).append(text or "")

        # Update profiles
        for domain, domain_txts in domain_texts.items():
            self.update_profile(domain_txts, domain)

        # Clean each text
        results: List[Optional[str]] = []
        for text, domain in texts_with_domains:
            if not text:
                results.append(None)
                continue

            cleaned = self.clean_document(text, domain)

            if len(cleaned) < min_text_len:
                results.append(None)
                continue

            if devanagari_ratio(cleaned) < min_devanagari:
                results.append(None)
                continue

            results.append(cleaned)

        return results

    @property
    def domain_count(self) -> int:
        return len(self._domain_profiles)

    def stats(self) -> dict:
        return {
            "domains_profiled": self.domain_count,
            "total_boilerplate_lines": sum(
                len(v) for v in self._domain_profiles.values()
            ),
        }


__all__ = [
    "clean_extracted_text",
    "BoilerplateDetector",
    "TOP_MENU_KEYWORDS",
    "JUNK_KEYWORDS",
    "BAD_PATTERNS",
]
